#!/bin/bash
## Work Directory: /home/git/html/
## User: git

### status
cat DOCTYPE.shtml                 | tee status/502-ganglia.html    >/dev/null
cat 502_header.shtml              | tee status/502-ganglia.html -a >/dev/null
cat header.shtml                  | sed "s/<li><!--CURRENT:ERR502-->/<li class=\"current\">/g" \
                                  | sed "s/<li><!--CURRENT:ERRPAGE-->/<li class=\"current\">/g" \
                                  | sed "s/<li><!--CURRENT:HOME-->/<li class=\"current\">/g" \
                                  | sed "s/<li><!--CURRENT:[^>]*-->/<li>/g" \
                                  | tee status/502-ganglia.html -a >/dev/null
cat status/502-ganglia_body.shtml | tee status/502-ganglia.html -a >/dev/null
cat footer.shtml                  | tee status/502-ganglia.html -a >/dev/null
cat jquery.shtml                  | tee status/502-ganglia.html -a >/dev/null
cat errorpage_footer.shtml        | tee status/502-ganglia.html -a >/dev/null
echo Generate status/502-ganglia.html
cat DOCTYPE.shtml                 | tee status/502-phpinfo.html    >/dev/null
cat 502_header.shtml              | tee status/502-phpinfo.html -a >/dev/null
cat header.shtml                  | sed "s/<li><!--CURRENT:ERR502-->/<li class=\"current\">/g" \
                                  | sed "s/<li><!--CURRENT:ERRPAGE-->/<li class=\"current\">/g" \
                                  | sed "s/<li><!--CURRENT:HOME-->/<li class=\"current\">/g" \
                                  | sed "s/<li><!--CURRENT:[^>]*-->/<li>/g" \
                                  | tee status/502-phpinfo.html -a >/dev/null
cat status/502-phpinfo_body.shtml | tee status/502-phpinfo.html -a >/dev/null
cat footer.shtml                  | tee status/502-phpinfo.html -a >/dev/null
cat jquery.shtml                  | tee status/502-phpinfo.html -a >/dev/null
cat errorpage_footer.shtml        | tee status/502-phpinfo.html -a >/dev/null
echo Generate status/502-phpinfo.html
cat DOCTYPE.shtml         | tee status/ddns-log-static.html    >/dev/null
cat ddns-log_header.shtml | tee status/ddns-log-static.html -a >/dev/null
cat header.shtml          | sed "s/<li><!--CURRENT:DDNS-->/<li class=\"current\">/g" \
                          | sed "s/<li><!--CURRENT:STATUS-->/<li class=\"current\">/g" \
                          | sed "s/<li><!--CURRENT:[^>]*-->/<li>/g" \
                          | tee status/ddns-log-static.html -a >/dev/null
cat ddns-log_body.shtml   | sed "s/<!--UPDATETIME-->/1970-01-01 08:00:00/g" \
                          | sed "s/<!--DATA-CATEGORIES:TIME:1-->/<a data-categories=\"01-07\">01\/07<\/a>/g" \
                          | sed "s/<!--DATA-CATEGORIES:TIME:2-->/<a data-categories=\"01-06\">01\/06<\/a>/g" \
                          | sed "s/<!--DATA-CATEGORIES:TIME:3-->/<a data-categories=\"01-05\">01\/05<\/a>/g" \
                          | sed "s/<!--DATA-CATEGORIES:TIME:4-->/<a data-categories=\"01-04\">01\/04<\/a>/g" \
                          | sed "s/<!--DATA-CATEGORIES:TIME:5-->/<a data-categories=\"01-03\">01\/03<\/a>/g" \
                          | sed "s/<!--DATA-CATEGORIES:TIME:6-->/<a data-categories=\"01-02\">01\/02<\/a>/g" \
                          | sed "s/<!--DATA-CATEGORIES:TIME:7-->/<a data-categories=\"01-01\">01\/01<\/a>/g" \
                          | tee status/ddns-log-static.html -a >/dev/null
cat footer.shtml          | tee status/ddns-log-static.html -a >/dev/null
cat jquery.shtml          | tee status/ddns-log-static.html -a >/dev/null
cat ddns-log_footer.shtml | tee status/ddns-log-static.html -a >/dev/null
echo Generate status/ddns-log-static.html
