#!/bin/bash
## Work Directory: /home/git/html/
## User: git

### www
cat DOCTYPE.shtml          | tee www/index.html    >/dev/null
cat www/index_header.shtml | tee www/index.html -a >/dev/null
cat header.shtml           | sed "s/<li><!--CURRENT:HOME-->/<li class=\"current\">/g" \
                           | sed "s/<li><!--CURRENT:[^>]*-->/<li>/g" \
                           | tee www/index.html -a >/dev/null
cat www/index_body.shtml   | tee www/index.html -a >/dev/null
cat footer.shtml           | tee www/index.html -a >/dev/null
cat jquery.shtml           | tee www/index.html -a >/dev/null
cat www/index_footer.shtml | tee www/index.html -a >/dev/null
echo Generate www/index.html
cat DOCTYPE.shtml          | tee www/index-ipv4.html    >/dev/null
cat www/index_header.shtml | tee www/index-ipv4.html -a >/dev/null
cat header.shtml           | sed "s/<li><!--CURRENT:HOME-IPV4-->/<li class=\"current\">/g" \
                           | sed "s/<li><!--CURRENT:HOME-->/<li class=\"current\">/g" \
                           | sed "s/<li><!--CURRENT:[^>]*-->/<li>/g" \
                           | tee www/index-ipv4.html -a >/dev/null
cat www/index_body.shtml   | tee www/index-ipv4.html -a >/dev/null
cat footer.shtml           | tee www/index-ipv4.html -a >/dev/null
cat jquery.shtml           | tee www/index-ipv4.html -a >/dev/null
cat www/index_footer.shtml | tee www/index-ipv4.html -a >/dev/null
echo Generate www/index-ipv4.html
cat DOCTYPE.shtml          | tee www/index-ipv6.html    >/dev/null
cat www/index_header.shtml | tee www/index-ipv6.html -a >/dev/null
cat header.shtml           | sed "s/<li><!--CURRENT:HOME-IPV6-->/<li class=\"current\">/g" \
                           | sed "s/<li><!--CURRENT:HOME-->/<li class=\"current\">/g" \
                           | sed "s/<li><!--CURRENT:[^>]*-->/<li>/g" \
                           | tee www/index-ipv6.html -a >/dev/null
cat www/index_body.shtml   | tee www/index-ipv6.html -a >/dev/null
cat footer.shtml           | tee www/index-ipv6.html -a >/dev/null
cat jquery.shtml           | tee www/index-ipv6.html -a >/dev/null
cat www/index_footer.shtml | tee www/index-ipv6.html -a >/dev/null
echo Generate www/index-ipv6.html
rm www/index_header.shtml www/index_body.shtml www/index_footer.shtml
cat DOCTYPE.shtml            | tee www/setting.html    >/dev/null
cat www/setting_header.shtml | tee www/setting.html -a >/dev/null
cat header.shtml             | sed "s/<li><!--CURRENT:SETTING-->/<li class=\"current\">/g" \
                             | sed "s/<li><!--CURRENT:HOME-->/<li class=\"current\">/g" \
                             | sed "s/<li><!--CURRENT:[^>]*-->/<li>/g" \
                             | tee www/setting.html -a >/dev/null
cat www/setting_body.shtml   | tee www/setting.html -a >/dev/null
cat footer.shtml             | tee www/setting.html -a >/dev/null
cat jquery.shtml             | tee www/setting.html -a >/dev/null
cat www/setting_footer.shtml | tee www/setting.html -a >/dev/null
echo Generate www/setting.html
rm www/setting_header.shtml www/setting_body.shtml www/setting_footer.shtml
