#!/bin/bash

### Master
config/sign-commit DOCTYPE.shtml          | tee 400.html    >/dev/null
config/sign-commit 400_header.shtml       | tee 400.html -a >/dev/null
config/sign-commit header.shtml           | tee 400.html -a >/dev/null
config/sign-commit 400_body.shtml         | tee 400.html -a >/dev/null
config/sign-commit footer.shtml           | tee 400.html -a >/dev/null
config/sign-commit jquery.shtml           | tee 400.html -a >/dev/null
config/sign-commit errorpage_footer.shtml | tee 400.html -a >/dev/null
echo Sign 400.html
config/sign-commit DOCTYPE.shtml          | tee 403.html    >/dev/null
config/sign-commit 403_header.shtml       | tee 403.html -a >/dev/null
config/sign-commit header.shtml           | tee 403.html -a >/dev/null
config/sign-commit 403_body.shtml         | tee 403.html -a >/dev/null
config/sign-commit footer.shtml           | tee 403.html -a >/dev/null
config/sign-commit jquery.shtml           | tee 403.html -a >/dev/null
config/sign-commit errorpage_footer.shtml | tee 403.html -a >/dev/null
echo Sign 403.html
config/sign-commit DOCTYPE.shtml          | tee 404.html    >/dev/null
config/sign-commit 404_header.shtml       | tee 404.html -a >/dev/null
config/sign-commit header.shtml           | tee 404.html -a >/dev/null
config/sign-commit 404_body.shtml         | tee 404.html -a >/dev/null
config/sign-commit footer.shtml           | tee 404.html -a >/dev/null
config/sign-commit jquery.shtml           | tee 404.html -a >/dev/null
config/sign-commit errorpage_footer.shtml | tee 404.html -a >/dev/null
echo Sign 404.html
config/sign-commit DOCTYPE.shtml          | tee 414.html    >/dev/null
config/sign-commit 414_header.shtml       | tee 414.html -a >/dev/null
config/sign-commit header.shtml           | tee 414.html -a >/dev/null
config/sign-commit 414_body.shtml         | tee 414.html -a >/dev/null
config/sign-commit footer.shtml           | tee 414.html -a >/dev/null
config/sign-commit jquery.shtml           | tee 414.html -a >/dev/null
config/sign-commit errorpage_footer.shtml | tee 414.html -a >/dev/null
echo Sign 414.html
config/sign-commit DOCTYPE.shtml          | tee 422.html    >/dev/null
config/sign-commit 422_header.shtml       | tee 422.html -a >/dev/null
config/sign-commit header.shtml           | tee 422.html -a >/dev/null
config/sign-commit 422_body.shtml         | tee 422.html -a >/dev/null
config/sign-commit footer.shtml           | tee 422.html -a >/dev/null
config/sign-commit jquery.shtml           | tee 422.html -a >/dev/null
config/sign-commit errorpage_footer.shtml | tee 422.html -a >/dev/null
echo Sign 422.html
config/sign-commit DOCTYPE.shtml          | tee 500.html    >/dev/null
config/sign-commit 500_header.shtml       | tee 500.html -a >/dev/null
config/sign-commit header.shtml           | tee 500.html -a >/dev/null
config/sign-commit 500_body.shtml         | tee 500.html -a >/dev/null
config/sign-commit footer.shtml           | tee 500.html -a >/dev/null
config/sign-commit jquery.shtml           | tee 500.html -a >/dev/null
config/sign-commit errorpage_footer.shtml | tee 500.html -a >/dev/null
echo Sign 500.html
config/sign-commit DOCTYPE.shtml          | tee 502.html    >/dev/null
config/sign-commit 502_header.shtml       | tee 502.html -a >/dev/null
config/sign-commit header.shtml           | tee 502.html -a >/dev/null
config/sign-commit 502_body.shtml         | tee 502.html -a >/dev/null
config/sign-commit footer.shtml           | tee 502.html -a >/dev/null
config/sign-commit jquery.shtml           | tee 502.html -a >/dev/null
config/sign-commit errorpage_footer.shtml | tee 502.html -a >/dev/null
echo Sign 502.html
config/sign-commit DOCTYPE.shtml          | tee 503.html    >/dev/null
config/sign-commit 503_header.shtml       | tee 503.html -a >/dev/null
config/sign-commit header.shtml           | tee 503.html -a >/dev/null
config/sign-commit 503_body.shtml         | tee 503.html -a >/dev/null
config/sign-commit footer.shtml           | tee 503.html -a >/dev/null
config/sign-commit jquery.shtml           | tee 503.html -a >/dev/null
config/sign-commit errorpage_footer.shtml | tee 503.html -a >/dev/null
echo Sign 503.html
config/sign-commit DOCTYPE.shtml          | tee 504.html    >/dev/null
config/sign-commit 504_header.shtml       | tee 504.html -a >/dev/null
config/sign-commit header.shtml           | tee 504.html -a >/dev/null
config/sign-commit 504_body.shtml         | tee 504.html -a >/dev/null
config/sign-commit footer.shtml           | tee 504.html -a >/dev/null
config/sign-commit jquery.shtml           | tee 504.html -a >/dev/null
config/sign-commit errorpage_footer.shtml | tee 504.html -a >/dev/null
echo Sign 504.html
