#!/bin/bash

### static
config/sign-commit DOCTYPE.shtml                 | tee static/400.html    >/dev/null
config/sign-commit static/400_header.shtml       | tee static/400.html -a >/dev/null
config/sign-commit header.shtml                  | tee static/400.html -a >/dev/null
config/sign-commit 400_body.shtml                | tee static/400.html -a >/dev/null
config/sign-commit footer.shtml                  | tee static/400.html -a >/dev/null
config/sign-commit static/jquery.shtml           | tee static/400.html -a >/dev/null
config/sign-commit static/errorpage_footer.shtml | tee static/400.html -a >/dev/null
config/sign-commit config/post-html/A06*         | tee static/400.html -a >/dev/null
echo Sign static/400.html
config/sign-commit DOCTYPE.shtml                 | tee static/403.html    >/dev/null
config/sign-commit static/403_header.shtml       | tee static/403.html -a >/dev/null
config/sign-commit header.shtml                  | tee static/403.html -a >/dev/null
config/sign-commit 403_body.shtml                | tee static/403.html -a >/dev/null
config/sign-commit footer.shtml                  | tee static/403.html -a >/dev/null
config/sign-commit static/jquery.shtml           | tee static/403.html -a >/dev/null
config/sign-commit static/errorpage_footer.shtml | tee static/403.html -a >/dev/null
config/sign-commit config/post-html/A06*         | tee static/403.html -a >/dev/null
echo Sign static/403.html
config/sign-commit DOCTYPE.shtml                 | tee static/404.html    >/dev/null
config/sign-commit static/404_header.shtml       | tee static/404.html -a >/dev/null
config/sign-commit header.shtml                  | tee static/404.html -a >/dev/null
config/sign-commit 404_body.shtml                | tee static/404.html -a >/dev/null
config/sign-commit footer.shtml                  | tee static/404.html -a >/dev/null
config/sign-commit static/jquery.shtml           | tee static/404.html -a >/dev/null
config/sign-commit static/errorpage_footer.shtml | tee static/404.html -a >/dev/null
config/sign-commit config/post-html/A06*         | tee static/404.html -a >/dev/null
echo Sign static/404.html
config/sign-commit DOCTYPE.shtml                 | tee static/414.html    >/dev/null
config/sign-commit static/414_header.shtml       | tee static/414.html -a >/dev/null
config/sign-commit header.shtml                  | tee static/414.html -a >/dev/null
config/sign-commit 414_body.shtml                | tee static/414.html -a >/dev/null
config/sign-commit footer.shtml                  | tee static/414.html -a >/dev/null
config/sign-commit static/jquery.shtml           | tee static/414.html -a >/dev/null
config/sign-commit static/errorpage_footer.shtml | tee static/414.html -a >/dev/null
config/sign-commit config/post-html/A06*         | tee static/414.html -a >/dev/null
echo Sign static/414.html
config/sign-commit DOCTYPE.shtml                 | tee static/422.html    >/dev/null
config/sign-commit static/422_header.shtml       | tee static/422.html -a >/dev/null
config/sign-commit header.shtml                  | tee static/422.html -a >/dev/null
config/sign-commit 422_body.shtml                | tee static/422.html -a >/dev/null
config/sign-commit footer.shtml                  | tee static/422.html -a >/dev/null
config/sign-commit static/jquery.shtml           | tee static/422.html -a >/dev/null
config/sign-commit static/errorpage_footer.shtml | tee static/422.html -a >/dev/null
config/sign-commit config/post-html/A06*         | tee static/422.html -a >/dev/null
echo Sign static/422.html
config/sign-commit DOCTYPE.shtml                 | tee static/500.html    >/dev/null
config/sign-commit static/500_header.shtml       | tee static/500.html -a >/dev/null
config/sign-commit header.shtml                  | tee static/500.html -a >/dev/null
config/sign-commit 500_body.shtml                | tee static/500.html -a >/dev/null
config/sign-commit footer.shtml                  | tee static/500.html -a >/dev/null
config/sign-commit static/jquery.shtml           | tee static/500.html -a >/dev/null
config/sign-commit static/errorpage_footer.shtml | tee static/500.html -a >/dev/null
config/sign-commit config/post-html/A06*         | tee static/500.html -a >/dev/null
echo Sign static/500.html
config/sign-commit DOCTYPE.shtml                 | tee static/502.html    >/dev/null
config/sign-commit static/502_header.shtml       | tee static/502.html -a >/dev/null
config/sign-commit header.shtml                  | tee static/502.html -a >/dev/null
config/sign-commit 502_body.shtml                | tee static/502.html -a >/dev/null
config/sign-commit footer.shtml                  | tee static/502.html -a >/dev/null
config/sign-commit static/jquery.shtml           | tee static/502.html -a >/dev/null
config/sign-commit static/errorpage_footer.shtml | tee static/502.html -a >/dev/null
config/sign-commit config/post-html/A06*         | tee static/502.html -a >/dev/null
echo Sign static/502.html
config/sign-commit DOCTYPE.shtml                 | tee static/503.html    >/dev/null
config/sign-commit static/503_header.shtml       | tee static/503.html -a >/dev/null
config/sign-commit header.shtml                  | tee static/503.html -a >/dev/null
config/sign-commit 503_body.shtml                | tee static/503.html -a >/dev/null
config/sign-commit footer.shtml                  | tee static/503.html -a >/dev/null
config/sign-commit static/jquery.shtml           | tee static/503.html -a >/dev/null
config/sign-commit static/errorpage_footer.shtml | tee static/503.html -a >/dev/null
config/sign-commit config/post-html/A06*         | tee static/503.html -a >/dev/null
echo Sign static/503.html
config/sign-commit DOCTYPE.shtml                 | tee static/504.html    >/dev/null
config/sign-commit static/504_header.shtml       | tee static/504.html -a >/dev/null
config/sign-commit header.shtml                  | tee static/504.html -a >/dev/null
config/sign-commit 504_body.shtml                | tee static/504.html -a >/dev/null
config/sign-commit footer.shtml                  | tee static/504.html -a >/dev/null
config/sign-commit static/jquery.shtml           | tee static/504.html -a >/dev/null
config/sign-commit static/errorpage_footer.shtml | tee static/504.html -a >/dev/null
config/sign-commit config/post-html/A06*         | tee static/504.html -a >/dev/null
echo Sign static/504.html
config/sign-commit DOCTYPE.shtml             | tee static/index.html    >/dev/null
config/sign-commit static/index_header.shtml | tee static/index.html -a >/dev/null
config/sign-commit header.shtml              | tee static/index.html -a >/dev/null
config/sign-commit static/index_body.shtml   | tee static/index.html -a >/dev/null
config/sign-commit footer.shtml              | tee static/index.html -a >/dev/null
config/sign-commit static/jquery.shtml       | tee static/index.html -a >/dev/null
config/sign-commit static/index_footer.shtml | tee static/index.html -a >/dev/null
config/sign-commit config/post-html/A06*     | tee static/index.html -a >/dev/null
echo Sign static/index.html
config/sign-commit DOCTYPE.shtml             | tee static/index-freeshell.html    >/dev/null
config/sign-commit static/index_header.shtml | tee static/index-freeshell.html -a >/dev/null
config/sign-commit header.shtml              | tee static/index-freeshell.html -a >/dev/null
config/sign-commit static/index_body.shtml   | tee static/index-freeshell.html -a >/dev/null
config/sign-commit footer.shtml              | tee static/index-freeshell.html -a >/dev/null
config/sign-commit static/jquery.shtml       | tee static/index-freeshell.html -a >/dev/null
config/sign-commit static/index_footer.shtml | tee static/index-freeshell.html -a >/dev/null
config/sign-commit config/post-html/A06*     | tee static/index-freeshell.html -a >/dev/null
echo Sign static/index-freeshell.html
config/sign-commit DOCTYPE.shtml             | tee static/index-hangzhou.html    >/dev/null
config/sign-commit static/index_header.shtml | tee static/index-hangzhou.html -a >/dev/null
config/sign-commit header.shtml              | tee static/index-hangzhou.html -a >/dev/null
config/sign-commit static/index_body.shtml   | tee static/index-hangzhou.html -a >/dev/null
config/sign-commit footer.shtml              | tee static/index-hangzhou.html -a >/dev/null
config/sign-commit static/jquery.shtml       | tee static/index-hangzhou.html -a >/dev/null
config/sign-commit static/index_footer.shtml | tee static/index-hangzhou.html -a >/dev/null
config/sign-commit config/post-html/A06*     | tee static/index-hangzhou.html -a >/dev/null
echo Sign static/index-hangzhou.html
config/sign-commit DOCTYPE.shtml             | tee static/index-static.html    >/dev/null
config/sign-commit static/index_header.shtml | tee static/index-static.html -a >/dev/null
config/sign-commit header.shtml              | tee static/index-static.html -a >/dev/null
config/sign-commit static/index_body.shtml   | tee static/index-static.html -a >/dev/null
config/sign-commit footer.shtml              | tee static/index-static.html -a >/dev/null
config/sign-commit static/jquery.shtml       | tee static/index-static.html -a >/dev/null
config/sign-commit static/index_footer.shtml | tee static/index-static.html -a >/dev/null
config/sign-commit config/post-html/A06*     | tee static/index-static.html -a >/dev/null
echo Sign static/index-static.html
