#!/bin/bash
## Work Directory: /home/git/html/
## User: git

### static/ftp/static
config/sign-commit DOCTYPE.shtml                                 | tee static/ftp/static/403-deny-files.html    >/dev/null
config/sign-commit static/ftp/static/403-deny-files_header.shtml | tee static/ftp/static/403-deny-files.html -a >/dev/null
config/sign-commit header.shtml                                  | tee static/ftp/static/403-deny-files.html -a >/dev/null
config/sign-commit 403_body.shtml                                | tee static/ftp/static/403-deny-files.html -a >/dev/null
config/sign-commit footer.shtml                                  | tee static/ftp/static/403-deny-files.html -a >/dev/null
config/sign-commit jquery.shtml                                  | tee static/ftp/static/403-deny-files.html -a >/dev/null
config/sign-commit errorpage_footer.shtml                        | tee static/ftp/static/403-deny-files.html -a >/dev/null
echo Sign static/ftp/static/403-deny-files.html
config/sign-commit DOCTYPE.shtml                          | tee static/ftp/static/502-image.html    >/dev/null
config/sign-commit 502_header.shtml                       | tee static/ftp/static/502-image.html -a >/dev/null
config/sign-commit header.shtml                           | tee static/ftp/static/502-image.html -a >/dev/null
config/sign-commit static/ftp/static/502-image_body.shtml | tee static/ftp/static/502-image.html -a >/dev/null
config/sign-commit footer.shtml                           | tee static/ftp/static/502-image.html -a >/dev/null
config/sign-commit jquery.shtml                           | tee static/ftp/static/502-image.html -a >/dev/null
config/sign-commit errorpage_footer.shtml                 | tee static/ftp/static/502-image.html -a >/dev/null
echo Sign static/ftp/static/502-image.html
config/sign-commit DOCTYPE.shtml                          | tee static/ftp/static/502-index.html    >/dev/null
config/sign-commit 502_header.shtml                       | tee static/ftp/static/502-index.html -a >/dev/null
config/sign-commit header.shtml                           | tee static/ftp/static/502-index.html -a >/dev/null
config/sign-commit static/ftp/static/502-index_body.shtml | tee static/ftp/static/502-index.html -a >/dev/null
config/sign-commit footer.shtml                           | tee static/ftp/static/502-index.html -a >/dev/null
config/sign-commit jquery.shtml                           | tee static/ftp/static/502-index.html -a >/dev/null
config/sign-commit errorpage_footer.shtml                 | tee static/ftp/static/502-index.html -a >/dev/null
echo Sign static/ftp/static/502-index.html
config/sign-commit DOCTYPE.shtml                             | tee static/ftp/static/502-markdown.html    >/dev/null
config/sign-commit 502_header.shtml                          | tee static/ftp/static/502-markdown.html -a >/dev/null
config/sign-commit header.shtml                              | tee static/ftp/static/502-markdown.html -a >/dev/null
config/sign-commit static/ftp/static/502-markdown_body.shtml | tee static/ftp/static/502-markdown.html -a >/dev/null
config/sign-commit footer.shtml                              | tee static/ftp/static/502-markdown.html -a >/dev/null
config/sign-commit jquery.shtml                              | tee static/ftp/static/502-markdown.html -a >/dev/null
config/sign-commit errorpage_footer.shtml                    | tee static/ftp/static/502-markdown.html -a >/dev/null
echo Sign static/ftp/static/502-markdown.html
config/sign-commit DOCTYPE.shtml                             | tee static/ftp/static/502-prettify.html    >/dev/null
config/sign-commit 502_header.shtml                          | tee static/ftp/static/502-prettify.html -a >/dev/null
config/sign-commit header.shtml                              | tee static/ftp/static/502-prettify.html -a >/dev/null
config/sign-commit static/ftp/static/502-prettify_body.shtml | tee static/ftp/static/502-prettify.html -a >/dev/null
config/sign-commit footer.shtml                              | tee static/ftp/static/502-prettify.html -a >/dev/null
config/sign-commit jquery.shtml                              | tee static/ftp/static/502-prettify.html -a >/dev/null
config/sign-commit errorpage_footer.shtml                    | tee static/ftp/static/502-prettify.html -a >/dev/null
echo Sign static/ftp/static/502-prettify.html
