#!/bin/bash
if [ "upgrade"x == "$1"x ] ; then
  echo git pull remote branch
  commit1=$(git show --summary | grep commit | awk '{print $2}')
  for (( i=0 ; i < 5 ; i++ )) ; do
    if git pull ; then
      commit2=$(git show --summary | grep commit | awk '{print $2}')
      if [ "$commit1"x == "$commit2"x ] ; then
        exit 16
      else
        exit 0
      fi
    fi
    echo pull remote branch again
  done
  exit 1
else
  CURDIR=$(pwd)
  GITDIR=$CURDIR/.git/
  WOKDIR=/home/git/html
  echo calling config/make
  if [ -e $WOKDIR ] ; then
    rm -fr $WOKDIR
  fi
  mkdir $WOKDIR
  cp $CURDIR/* $WOKDIR/ -PR
  cd $WOKDIR/
  echo calling config/post-events
  GIT_WORK_TREE=$WOKDIR GIT_DIR=$GITDIR $WOKDIR/config/post-events
  echo complate!
fi
