#!/bin/bash
CURDIR=$(pwd)
WOKDIR=/home/git/html
echo calling post-receive
if [ -e $WOKDIR ] ; then
  rm -fr $WOKDIR
fi
mkdir $WOKDIR
GIT_WORK_TREE=$WOKDIR git checkout -f
cp -f $WOKDIR/config/post-receive $0
cd $WOKDIR/
echo calling config/post-events
GIT_WORK_TREE=$WOKDIR GIT_DIR=$GITDIR $WOKDIR/config/post-events
echo complate!
