#!/bin/bash
## Work Directory: /home/git/html/
## User: git

## Generate HTML5 document
echo call config/post-html/
run-parts --report config/post-html

## port another page
echo call config/post-another
config/post-another

## resume zh_TW page
echo call config/post-cconv
config/post-cconv

## remove Intermediate files
echo "remove *.shtml and *.phps"
for file in $(find -P */ -type f \( -name '*.shtml' -or -name '*.phps' \) -print) ; do
  if [ -f $file ] ; then
    rm $file
    echo "rm: $file"
  fi
done

## Create Hash
echo call config/post-hash startup
config/post-hash startup

#### Hash static directory
echo call config/post-hash TIMESTAMP
for file in $(find -P ./ -type f \( -name '*.html' -or -name '*.php' -or -name '*.css' -or -name '*.js' -or -name '*.json' -or -name '*.md' \) -print) ; do
  if [ ! -L $file ] ; then
    config/post-hash TIMESTAMP $file
  fi
done

### Hash static resources
echo call config/post-hash STANDARD
for file in $(find -P ./ -type f \( -name '*.html' -or -name '*.php' \) -print) ; do
  if [ ! -L $file ] ; then
    config/post-hash STANDARD $file
    sed -i 's/<!--\(\/\| end\| \*\)[^!<>]*-->//;s/^[[:space:]]*//;/^$/d' $file
  fi
done
sed -i 's/<!--\(\/\| end\| \*\)[^!<>]*-->//;s/^[[:space:]]*//;/^$/d' DOCTYPE.shtml

### Reset static resources timestamp (last modified)
echo call config/post-touch
for file in $(find -P ./ \( -type f -or -type d \) -print) ; do
  config/post-touch $file
done
