#!/bin/bash
echo calling post-receive
rm -fr /home/git/html/
mkdir /home/git/html/
GIT_WORK_TREE=/home/git/html git checkout -f
cp -f /home/git/html/config/post-receive $0
chmod 755 $0
cd /tmp/
cd /home/git/html/
echo calling post-events
chmod 755 /home/git/html/config/post-events
/home/git/html/config/post-events
echo complate!
