#!/bin/bash
cd `dirname $0`
## Work Directory: /home/git/html/config/
## User: git

## Generate Table
if host mirrors.lug >/tmp/ddns.tmp; then
  echo "<div class=\"one-fourth\">`date '+%F %T'`</div><div class=\"three-fourth last\" style=\"color:#808000\"><b>`cat /tmp/ddns.tmp | awk 'NR==1'` (1)</b></div><hr class=\"clear\" style=\"padding:0;\"/>" >>/tmp/ddns
elif host mirrors.lug >/tmp/ddns.tmp; then
  echo "<div class=\"one-fourth\">`date '+%F %T'`</div><div class=\"three-fourth last\" style=\"color:#806020\"><b>`cat /tmp/ddns.tmp | awk 'NR==1'` (2)</b></div><hr class=\"clear\" style=\"padding:0;\"/>" >>/tmp/ddns
elif host mirrors.lug >/tmp/ddns.tmp; then
  echo "<div class=\"one-fourth\">`date '+%F %T'`</div><div class=\"three-fourth last\" style=\"color:#804040\"><b>`cat /tmp/ddns.tmp | awk 'NR==1'` (3)</b></div><hr class=\"clear\" style=\"padding:0;\"/>" >>/tmp/ddns
elif host mirrors.lug >/tmp/ddns.tmp; then
  echo "<div class=\"one-fourth\">`date '+%F %T'`</div><div class=\"three-fourth last\" style=\"color:#802060\"><b>`cat /tmp/ddns.tmp | awk 'NR==1'` (4)</b></div><hr class=\"clear\" style=\"padding:0;\"/>" >>/tmp/ddns
elif host mirrors.lug >/tmp/ddns.tmp; then
  echo "<div class=\"one-fourth\">`date '+%F %T'`</div><div class=\"three-fourth last\" style=\"color:#800080\"><b>`cat /tmp/ddns.tmp | awk 'NR==1'` (5)</b></div><hr class=\"clear\" style=\"padding:0;\"/>" >>/tmp/ddns
else
  echo "<div class=\"one-fourth\">`date '+%F %T'`</div>`/home/git/update-ddns 1``/home/git/update-ddns 2``/home/git/update-ddns 3`<hr class=\"clear\" style=\"padding:0;\"/>" >>/tmp/ddns
fi

## Generate ddns-log.html
### /tmp/ddns-log.html
cat ../ddns-log_header.shtml  | tee /tmp/ddns-log.html    >/dev/null
cat ../header.shtml           | sed "s/<!--CURRENT:DDNS-->/<li class=\"current\">/g" \
                              | sed "s/<!--CURRENT:STATUS-->/<li class=\"current\">/g" \
                              | sed "s/<!--CURRENT:[^>]*-->/<li>/g" \
                              | tee /tmp/ddns-log.html -a >/dev/null
cat ../ddns-log_body.shtml    | sed "s/<!--UPDATETIME-->/`date '+%F %T'`/g" \
                              | tee /tmp/ddns-log.html -a >/dev/null
cat /tmp/ddns                 | tee /tmp/ddns-log.html -a >/dev/null
echo "</div>"                 | tee /tmp/ddns-log.html -a >/dev/null
cat ../footer.shtml           | tee /tmp/ddns-log.html -a >/dev/null
cat ../errorpage_footer.shtml | tee /tmp/ddns-log.html -a >/dev/null
