#!/bin/bash
cd `dirname $0`
## Work Directory: /home/git/html/config/
## User: git

## Generate Table
if host mirrors.lug >/tmp/ddns.tmp; then
  echo "<div class=\"one-fourth time\">`date '+%F %T'`</div><div class=\"three-fourth last vpn1\">`cat /tmp/ddns.tmp | awk 'NR==1'`</div><hr class=\"clear\"/>" >>/tmp/ddns
elif host mirrors.lug >/tmp/ddns.tmp; then
  echo "<div class=\"one-fourth time\">`date '+%F %T'`</div><div class=\"three-fourth last vpn2>\"`cat /tmp/ddns.tmp | awk 'NR==1'`</div><hr class=\"clear\"/>" >>/tmp/ddns
elif host mirrors.lug >/tmp/ddns.tmp; then
  echo "<div class=\"one-fourth time\">`date '+%F %T'`</div><div class=\"three-fourth last vpn3\">`cat /tmp/ddns.tmp | awk 'NR==1'`</div><hr class=\"clear\"/>" >>/tmp/ddns
elif host mirrors.lug >/tmp/ddns.tmp; then
  echo "<div class=\"one-fourth time\">`date '+%F %T'`</div><div class=\"three-fourth last vpn4\">`cat /tmp/ddns.tmp | awk 'NR==1'`</div><hr class=\"clear\"/>" >>/tmp/ddns
elif host mirrors.lug >/tmp/ddns.tmp; then
  echo "<div class=\"one-fourth time\">`date '+%F %T'`</div><div class=\"three-fourth last vpn5\">`cat /tmp/ddns.tmp | awk 'NR==1'`</div><hr class=\"clear\"/>" >>/tmp/ddns
else
  echo "<div class=\"one-fourth time\">`date '+%F %T'`</div>`/home/git/update-ddns 1``/home/git/update-ddns 2``/home/git/update-ddns 3`<hr class=\"clear\"/>" >>/tmp/ddns
fi
tail -n 144 /tmp/ddns

## Generate ddns-log.html
### /tmp/ddns-log.html
cat ../ddns-log_header.shtml  | tee /tmp/ddns-log.html    >/dev/null
cat ../header.shtml           | sed "s/<!--CURRENT:DDNS-->/<li class=\"current\">/g" \
                              | sed "s/<!--CURRENT:STATUS-->/<li class=\"current\">/g" \
                              | sed "s/<!--CURRENT:[^>]*-->/<li>/g" \
                              | tee /tmp/ddns-log.html -a >/dev/null
cat ../ddns-log_body.shtml    | sed "s/<!--UPDATETIME-->/`date '+%F %T'`/g" \
                              | tee /tmp/ddns-log.html -a >/dev/null
cat /tmp/ddns                 | tee /tmp/ddns-log.html -a >/dev/null
echo "</div>"                 | tee /tmp/ddns-log.html -a >/dev/null
cat ../footer.shtml           | tee /tmp/ddns-log.html -a >/dev/null
cat ../errorpage_footer.shtml | tee /tmp/ddns-log.html -a >/dev/null
